### ISSUE TITLE
Recursive search fails and hangs for ./ imports

### ISSUE THREAD

**Issue by propercoil** [poanetwork/solidity-flattener#24] opened 2018-01-30 19:13 UTC
The recursive search for imports such as `import './BasicToken.sol';` fails and hangs.

For example it hangs like so after:

```
!!!zeppelin-solidity/contracts/token/StandardToken.sol SOURCE FILE NOT FOUND. TRY TO FIND IT RECURSIVELY!!!
###zeppelin-solidity/contracts/token/StandardToken.sol SOURCE FILE FOUND###
!!!../myproject/node_modules/zeppelin-solidity/contracts/token/./BasicToken.sol SOURCE FILE NOT FOUND. TRY TO FIND IT RECURSIVELY!!!
```

**Comment by lingqingmeng** [comment] 2018-01-31 01:49
Had to resolve it by manually replacing the imported lines and copying and pasting the contract it's trying to import for Zeppelin.

**Comment by lingqingmeng** [comment] 2018-01-31 01:51
@propercoil 

@vbaranov 
I believe the issue is you're not parsing dot dots when they exist in the middle of a dir path
```
###./TestToken.sol SOURCE FILE FOUND###
!!!../../Iconiccorp/solidity-truffle-ico/node_modules/zeppelin-solidity/contracts/token/../ownership/Ownable.sol SOURCE FILE NOT FOUND. TRY TO FIND IT RECURSIVELY!!!
^[[A^C
```

```
> node index.js "../../Iconiccorp/solidity-truffle-ico/contracts/TestCrowdsale.sol"

!!!zeppelin-solidity/contracts/crowdsale/Crowdsale.sol SOURCE FILE NOT FOUND. TRY TO FIND IT RECURSIVELY!!!
###zeppelin-solidity/contracts/crowdsale/Crowdsale.sol SOURCE FILE FOUND###
!!!zeppelin-solidity/contracts/token/MintableToken.sol SOURCE FILE NOT FOUND. TRY TO FIND IT RECURSIVELY!!!
###zeppelin-solidity/contracts/token/MintableToken.sol SOURCE FILE FOUND###
###./TestToken.sol SOURCE FILE FOUND###
Success! Flat file is generated to ./out directory
```

Even after this step, I still had to copy and paste `ERC20Basic`, `BasicToken`, and `ERC20`  into the top of the combined file.

**Comment by vbaranov** [comment] 2018-01-31 21:12
@propercoil could you specify, do you have this file
>../myproject/node_modules/zeppelin-solidity/contracts/token/BasicToken.sol

in your project?

I mean, did you `npm i zeppelin-solidity`  before starting flattener?

If yes, could you disclose your project folders structure? 

@lingqingmeng 
>I believe the issue is you're not parsing dot dots when they exist in the middle of a dir path

I believe it should parse, but let me check. Maybe, you can point me to the project with such structure to make tests?

**Comment by propercoil** [comment] 2018-02-01 16:20
@vbaranov the current OpenZepplin code has this structure. The files were there, when I modified them without ./ it worked. But it failed because of a different problem to complete all together:

> oracles-combine-solidity@1.0.0 start /Users/noko/oracles-combine-solidity
> node index.js "../myproject/contracts/XmrToken.sol"

```
!!!zeppelin-solidity/contracts/token/StandardToken.sol SOURCE FILE NOT FOUND. TRY TO FIND IT RECURSIVELY!!!
###zeppelin-solidity/contracts/token/StandardToken.sol SOURCE FILE FOUND###
!!!BasicToken.sol SOURCE FILE NOT FOUND. TRY TO FIND IT RECURSIVELY!!!
###BasicToken.sol SOURCE FILE FOUND###
!!!ERC20.sol SOURCE FILE NOT FOUND. TRY TO FIND IT RECURSIVELY!!!
###ERC20.sol SOURCE FILE FOUND###
!!!ERC20Basic.sol SOURCE FILE NOT FOUND. TRY TO FIND IT RECURSIVELY!!!
###ERC20Basic.sol SOURCE FILE FOUND###
!!!zeppelin-solidity/contracts/math/SafeMath.sol SOURCE FILE NOT FOUND. TRY TO FIND IT RECURSIVELY!!!
###zeppelin-solidity/contracts/math/SafeMath.sol SOURCE FILE FOUND###
!!!ERC20.sol SOURCE FILE NOT FOUND. TRY TO FIND IT RECURSIVELY!!!
###ERC20.sol SOURCE FILE FOUND###

/Users/noko/oracles-combine-solidity/node_modules/esprima/dist/esprima.js:5000
	            throw error;
	            ^
Error: Line 37: Invalid regular expression: missing /
    at ErrorHandler.constructError (/Users/noko/oracles-combine-solidity/node_modules/esprima/dist/esprima.js:5004:22)
    at ErrorHandler.createError (/Users/noko/oracles-combine-solidity/node_modules/esprima/dist/esprima.js:5020:27)
    at ErrorHandler.throwError (/Users/noko/oracles-combine-solidity/node_modules/esprima/dist/esprima.js:5027:21)
    at Scanner.throwUnexpectedToken (/Users/noko/oracles-combine-solidity/node_modules/esprima/dist/esprima.js:5155:35)
    at Scanner.scanRegExpBody (/Users/noko/oracles-combine-solidity/node_modules/esprima/dist/esprima.js:6130:23)
    at Scanner.scanRegExp (/Users/noko/oracles-combine-solidity/node_modules/esprima/dist/esprima.js:6195:29)
    at Tokenizer.getNextToken (/Users/noko/oracles-combine-solidity/node_modules/esprima/dist/esprima.js:6666:56)
    at Object.tokenize (/Users/noko/oracles-combine-solidity/node_modules/esprima/dist/esprima.js:154:36)
    at Object.parseRegEx (/Users/noko/oracles-combine-solidity/node_modules/decomment/lib/utils.js:37:13)
    at parser (/Users/noko/oracles-combine-solidity/node_modules/decomment/lib/parser.js:35:27)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! oracles-combine-solidity@1.0.0 start: `node index.js "../myproject/contracts/XmrToken.sol"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the oracles-combine-solidity@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/noko/.npm/_logs/2018-01-30T19_23_45_982Z-debug.log

```

**Comment by nickjuntilla** [comment] 2018-09-05 23:16
I am having the same problem with this and using OpenZeppelin library 

```
###./ERC721.sol SOURCE FILE FOUND###
###./ERC721BasicToken.sol SOURCE FILE FOUND###
###../../introspection/SupportsInterfaceWithLookup.sol SOURCE FILE FOUND###
!!!./../plouton_smart_contracts/contracts/token/ERC721/././ERC721Basic.sol SOURCE FILE NOT FOUND. TRY TO FIND IT RECURSIVELY!!!
###./../plouton_smart_contracts/contracts/token/ERC721/././ERC721Basic.sol SOURCE FILE FOUND###
!!!./../plouton_smart_contracts/contracts/token/ERC721/././ERC721Basic.sol SOURCE FILE NOT FOUND. TRY TO FIND IT RECURSIVELY!!!
###./../plouton_smart_contracts/contracts/token/ERC721/././ERC721Basic.sol SOURCE FILE FOUND###
!!!./../plouton_smart_contracts/contracts/token/ERC721/././ERC721Receiver.sol SOURCE FILE NOT FOUND. TRY TO FIND IT RECURSIVELY!!!
###./../plouton_smart_contracts/contracts/token/ERC721/././ERC721Receiver.sol SOURCE FILE FOUND###
!!!./../plouton_smart_contracts/contracts/token/ERC721/./../../math/SafeMath.sol SOURCE FILE NOT FOUND. TRY TO FIND IT RECURSIVELY!!!
###./../plouton_smart_contracts/contracts/token/ERC721/./../../math/SafeMath.sol SOURCE FILE FOUND###
!!!./../plouton_smart_contracts/contracts/token/ERC721/./../../AddressUtils.sol SOURCE FILE NOT FOUND. TRY TO FIND IT RECURSIVELY!!!
###./../plouton_smart_contracts/contracts/token/ERC721/./../../AddressUtils.sol SOURCE FILE FOUND###
!!!../../introspection/../plouton_smart_contracts/contracts/token/ERC721/../../introspection/./ERC165.sol SOURCE FILE NOT FOUND. TRY TO FIND IT RECURSIVELY!!!
###../../introspection/../plouton_smart_contracts/contracts/token/ERC721/../../introspection/./ERC165.sol SOURCE FILE FOUND###
Success! Flat file is generated to ./out directory
```

**Comment by vbaranov** [comment] 2018-09-06 14:52
@nickjuntilla  I've refactored the code of flattener. Could you check with the latest commit now?

**Comment by nickjuntilla** [comment] 2018-09-06 20:20
@vbaranov I'm getting this error now, perhaps glob-promise is not listed in the package:

```
Error: Cannot find module 'glob-promise'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/nicholasjuntilla/Documents/plouton/solidity-flattener/index.js:3:14)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
```

**Comment by vbaranov** [comment] 2018-09-07 08:50
Glad to hear. I will close this issue then. @propercoil @lingqingmeng if you are still experiencing this issue with the latest updates, please, let me know.

**Closed by vbaranov** 2018-09-07 08:50 UTC
